replicaCount: 1

image:
  repository: <your-docker-image>
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

env: 
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: 5432
  DB_USER: postgres
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_NAME: test-database
